language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed gthinesh/udagram-api-feed:v1
  - docker tag udagram-api-user gthinesh/udagram-api-user:v1
  - docker tag udagram-frontend gthinesh/udagram-frontend:v1
  - docker tag udagram-reverseproxy gthinesh/udagram-reverseproxy:v1
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push gthinesh/udagram-api-feed:v1
  - docker push gthinesh/udagram-api-user:v1
  - docker push gthinesh/udagram-frontend:v1
  - docker push gthinesh/udagram-reverseproxy:v1
## Do similar for other three images